ntfy_enabled="true"
ntfy_server="http://192.168.0.50:8080"
ntfy_topic="MyCAM"
ntfy_user="atl"
ntfy_pass="8i89r2d2"
ntfy_caption="%hostname, %datetime Temp: %soctemp"
ntfy_heif="false"
ntfy_priority="5"
