#!/bin/sh

# === ЗАГРУЗКА КОНФИГУРАЦИИ ===
CONFIG_FILE="/etc/webui/ntfy.conf"
if [ -e "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
else
    echo "Config file $CONFIG_FILE not found"
    exit 1
fi

# === ПРОВЕРКИ ===
if [ "$ntfy_enabled" != "true" ]; then
    echo "Sending to Ntfy is not enabled"
    exit 0
fi

if [ -z "$ntfy_topic" ]; then
    echo "Ntfy topic not found in config"
    exit 1
fi

# Значения по умолчанию
[ -z "$ntfy_server" ] && ntfy_server="https://ntfy.sh"
[ -z "$ntfy_priority" ] && ntfy_priority="3"

# Формирование текста сообщения
if [ -z "$ntfy_caption" ]; then
    ntfy_message="$(hostname -s), $(date +'%F %T')"
else
    ntfy_message="$(echo "$ntfy_caption" | sed "s/%hostname/$(hostname -s)/;s/%datetime/$(date +"%F %T")/;s/%soctemp/$(ipcinfo --temp)/")"
fi

# === СОЗДАНИЕ СНИМКА ===
filename="$(hostname -s | tr ' ' '-')"-"$(date +'%Y%m%d-%H%M%S')"

# Проверка формата (HEIF или JPG)
if [ "$ntfy_heif" = "true" ] && [ "$(yaml-cli -g .video0.codec)" = "h265" ]; then
    snapshot=/tmp/${filename}.heif
    wget -q -T1 localhost/image.heif -O "$snapshot"
else
    snapshot=/tmp/${filename}.jpg
    wget -q -T1 localhost/image.jpg -O "$snapshot"
fi

if [ ! -e "$snapshot" ]; then
    echo "Snapshot file not found"
    exit 1
fi

# === НАСТРОЙКА ПРОКСИ (Берет из стандартного конфига OpenIPC) ===
PROXY_OPTS=""
if [ -e "/etc/webui/proxy.conf" ]; then
    source /etc/webui/proxy.conf
    if [ "$openwall_proxy_enabled" = "true" ]; then
        PROXY_OPTS="--socks5-hostname ${socks5_host}:${socks5_port}"
        if [ -n "$socks5_login" ] && [ -n "$socks5_password" ]; then
            PROXY_OPTS="${PROXY_OPTS} --proxy-user ${socks5_login}:${socks5_password}"
        fi
    fi
fi

# === ОТПРАВКА В NTFY ===
command="curl -s"
command="${command} --connect-timeout 100"
command="${command} --max-time 100"

# Добавляем прокси, если есть
if [ -n "$PROXY_OPTS" ]; then
    command="${command} ${PROXY_OPTS}"
fi

# Заголовки
command="${command} -H 'Title: Motion Detected'"
command="${command} -H 'Priority: ${ntfy_priority}'"
command="${command} -H 'Tags: warning,rotating_light'"
command="${command} -H 'Message: ${ntfy_message}'"
command="${command} -H 'Filename: $(basename $snapshot)'"

# Отправка файла
command="${command} -T '${snapshot}'"
command="${command} '${ntfy_server}/${ntfy_topic}'"

# Логин и пароль
if [ -n "$ntfy_user" ]; then
    command="${command} -u ${ntfy_user}:${ntfy_pass}"
fi


# Выполняем
echo "$command"
eval "$command"

# Удаляем временный файл
rm -f "$snapshot"

exit 0